name: chat_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.1.14
  share_plus: ^10.1.4
  flutter_emoji: ^2.5.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  emoji_picker_flutter: ^1.6.3
  intl: ^0.18.1


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/google.png # ✅ Add this to load from assets (if downloaded)
    - assets/logo.png
