// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB7AR1N4Gfm6dTidvkDAmJY-odVjlI7UQ',
    appId: '1:813150458485:web:1dd5eaae13b54493ab5e3c',
    messagingSenderId: '813150458485',
    projectId: 'chatapp-72831',
    authDomain: 'chatapp-72831.firebaseapp.com',
    storageBucket: 'chatapp-72831.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACwSO-UiY976Cx38mf9lcPxCs8yRqT6gM',
    appId: '1:813150458485:android:2e31e606c4f332e6ab5e3c',
    messagingSenderId: '813150458485',
    projectId: 'chatapp-72831',
    storageBucket: 'chatapp-72831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_EUa_0IIfbbm9g4FJsME4yZz0RwDde1U',
    appId: '1:813150458485:ios:7a00d4d47bdd4addab5e3c',
    messagingSenderId: '813150458485',
    projectId: 'chatapp-72831',
    storageBucket: 'chatapp-72831.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_EUa_0IIfbbm9g4FJsME4yZz0RwDde1U',
    appId: '1:813150458485:ios:7a00d4d47bdd4addab5e3c',
    messagingSenderId: '813150458485',
    projectId: 'chatapp-72831',
    storageBucket: 'chatapp-72831.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB7AR1N4Gfm6dTidvkDAmJY-odVjlI7UQ',
    appId: '1:813150458485:web:53800cd756456813ab5e3c',
    messagingSenderId: '813150458485',
    projectId: 'chatapp-72831',
    authDomain: 'chatapp-72831.firebaseapp.com',
    storageBucket: 'chatapp-72831.firebasestorage.app',
  );
}
